application: starvingsounds-1091
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:                                                                   
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
- name: MySQLdb                                                            
  version: latest
  
handlers:
- url: /styles
  static_dir: styles
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /audio
  static_dir: audio
- url: /font
  static_dir: font
- url: /js
  static_dir: js
- url: /.*
  script: devcompany.application

builtins:
- remote_api: on
